on:
  push:
    branches: [main]
  pull_request:

name: Build
jobs:
  build-prover:
    defaults:
      run:
        working-directory: ./pkg/prover
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: Run Mage
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: -v build
          workdir: ./pkg/prover
